sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QpTtoiHwiybuylbdd64SZCME/OlvGm+DCID8vQYyAtVPHm2tY9EaM7rGRh897t+SnztwBEAV/epw86tYWIbmCMCs/rzXbfjJtbVE8nR0OiNBTty33bvk4ELaUGzLvocE/nw7uF9vffbZ0bw1j6mA/NLL8uLB56HbPygOsHXeTQAjpJfH1oetXzcDmb7lLd5f3U10XgGeWDwoX7unI64BMDiLESsSM20+RRXATDkQSINBQqS8p0y/+WUdhfEnWFCa9LlaVaVsjM3gGuwjOadCGfWSN3nj3Um8F3fmKa63f11nCpYGfynGZCIWMKR/QlnsIRbC/vDORxGX8+Aqp6kgW4WOrKlJIvHHC7nOpS8EBra/nwrG0tvhQAjzrxas5axY9yX4Jg/aGeBsYxNpjkFKges3DLpxKzPyISy/sikDWHneDEH+kYvCWXoByMsXV3zegHitZk5Ut155VqYYcSXOhPcuF4JWI78gyLgL6iEBsgM58RcuOr/ZZiZtX3784Gb+UBWl/jVM+oHLEMUiHMvdTprfMtx3rVkM9euSCfFfvfqy5sgBowPhGedbtTLH36u8tW8H1mg3bcH5B26jrRfPTZRaWXanSGXfrzwADUL66NyaeT+ydnEjOohmi/rQEqPdRsTy21j+hLRY+mXeOHwyh4rVLprurX2RgjepESfk5M8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Shuttle_506
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy